name: Build Psych Engine

on:
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.name }}
    strategy:
      matrix:
        include:
          - name: Android-Arm64
            os: ubuntu-24.04
            buildArgs: "android -D officialBuild -ONLY_ARM64 -final"
            artifactName: androidBuild-Arm64
            artifactPath: "export/release/android/bin/app/build/outputs/apk/release/*.apk"
            system: Android
          - name: Android-Armv7
            os: ubuntu-24.04
            buildArgs: "android -D officialBuild -ONLY_ARMV7 -final"
            artifactName: androidBuild-Armv7
            artifactPath: "export/release/android/bin/app/build/outputs/apk/release/*.apk"
            system: Android
          - name: Android-Both
            os: ubuntu-24.04
            buildArgs: "android -D officialBuild -final"
            artifactName: androidBuild-Both
            artifactPath: "export/release/android/bin/app/build/outputs/apk/release/*.apk"
            system: Android
          - name: iOS
            os: macos-14
            buildArgs: "ios -D finalBuild"
            artifactName: iOSBuild
            artifactPath: "export/release/ios/build/Release-iphoneos/*.ipa"
            system: iOS
          - name: iOS-Simulator
            os: macos-14
            buildArgs: "ios -D simulatorBuild"
            artifactName: iOSSimBuild
            artifactPath: "export/release/ios/build/Release-iphonesimulator/*.ipa"
            system: iOS

    runs-on: ${{ matrix.os }}

    env:
      HAXE_VERSION: 4.2.5
      PROJECT_NAME: PsychEngine

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1.2.0
        with:
          haxe-version: ${{ env.HAXE_VERSION }}

      - name: Setup Android NDK
        if: matrix.system == 'Android'
        id: setup-ndk
        uses: nttld/setup-ndk@main
        with:
          ndk-version: r27c
          add-to-path: false

      - name: Clean Haxelib & old builds
        run: |
          echo "🧹 Limpando Haxelib e builds antigos..."
          rm -rf ~/haxelib_cache
          rm -rf export/release

      - name: Install Libraries & Setup
        run: sh ./setup/unix.sh ${{ matrix.system }}

      - name: Configure Android
        if: matrix.system == 'Android'
        run: |
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT ${{ steps.setup-ndk.outputs.ndk-path }}
          haxelib run lime config JAVA_HOME $JAVA_HOME_17_X64
          haxelib run lime config ANDROID_SETUP true

      - name: Compile
        run: haxelib run lime build ${{ matrix.buildArgs }}

      - name: Make IPA For iOS Simulator
        if: matrix.system == 'iOS-Sim'
        run: |
          cd export/release/ios/build/Release-iphonesimulator
          mkdir Payload
          mv *.app Payload
          zip -r ${{ env.PROJECT_NAME }}.ipa Payload

      - name: Make IPA For iOS
        if: matrix.system == 'iOS'
        run: |
          cd export/release/ios/build/Release-iphoneos
          mkdir Payload
          mv *.app Payload
          zip -r ${{ env.PROJECT_NAME }}.ipa Payload

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.artifactName }}
          path: ${{ matrix.artifactPath }}
          if-no-files-found: error
